DROP TABLE IF EXISTS MED;
CREATE TABLE MED (ID INTEGER PRIMARY KEY, NAME VARCHAR(128), INN VARCHAR(128));
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '1' , 'Am-500' , 'Amikacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '2' , 'Amx/Clv-250/125' , 'Amoxicillin / Clavulanic acid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '3' , 'Amx/Clv-500/125' , 'Amoxicillin / Clavulanic acid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '4' , 'Amx/Clv-875/125' , 'Amoxicillin / Clavulanic acid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '5' , 'Bdq-100' , 'Bedaquiline' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '6' , 'Cfz-100' , 'Clofazimine' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '7' , 'Cfz-50' , 'Clofazimine' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '8' , 'Clr-250' , 'Clarithromycin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '9' , 'Clr-500' , 'Clarithromycin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '10' , 'Cm-0.5' , 'Capreomycin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '11' , 'Cm-0.75' , 'Capreomycin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '12' , 'Cm-1' , 'Capreomycin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '13' , 'Cs-125' , 'Cycloserine' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '14' , 'Cs-250' , 'Cycloserine' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '15' , 'Dlm-50' , 'Delamanid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '16' , 'E-100' , 'Ethambutol' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '17' , 'E-400' , 'Ethambutol' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '18' , 'E-800' , 'Ethambutol' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '19' , 'EH-400/150' , 'Ethambutol/Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '20' , 'Eto-125' , 'Ethionamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '21' , 'Eto-250' , 'Ethionamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '22' , 'H-100' , 'Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '23' , 'H-300' , 'Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '24' , 'HPST-Q-TIB' , 'Isoniazid/Pyridoxine hydrochl/Sulfamethoxazole/Trimethoprim' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '25' , 'Imp/Cls-500/500' , 'Imipenem / Cilastatin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '26' , 'Km-0.5' , 'Kanamycin Sulphate' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '27' , 'Km-1' , 'Kanamycin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '28' , 'Lfx-100' , 'Levofloxacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '29' , 'Lfx-250' , 'Levofloxacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '30' , 'Lfx-500' , 'Levofloxacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '31' , 'Lfx-750' , 'Levofloxacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '32' , 'Lnz-600' , 'Linezolid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '33' , 'Mfx-100' , 'Moxifloxacin (hydrochloride)' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '34' , 'Mfx-400' , 'Moxifloxacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '35' , 'Mrp-1' , 'Meropenem' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '36' , 'Ofx-200' , 'Ofloxacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '37' , 'Ofx-400' , 'Ofloxacin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '38' , 'PAS-(H)-4' , 'PAS Acid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '39' , 'PAS-(Na)-100' , 'PAS Sodium Salt' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '40' , 'PAS-(Na)-4' , 'PAS Sodium Salt' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '41' , 'Pto-250' , 'Prothionamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '42' , 'Pyr(B6)-100' , 'Pyridoxine' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '43' , 'Pyr(B6)-50' , 'Pyridoxine' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '44' , 'R-150' , 'Rifampicin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '45' , 'R-300' , 'Rifampicin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '46' , 'RH-150/150' , 'Rifampicin/Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '47' , 'RH-150/75' , 'Rifampicin/Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '48' , 'RH-300/150' , 'Rifampicin/Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '49' , 'RH-60/30' , 'Rifampicin/Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '50' , 'RH-60/60' , 'Rifampicin/Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '51' , 'RH-75/50' , 'Rifampicin/Isoniazid' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '52' , 'RHE-150/75/275' , 'Rifampicin/Isoniazid/Ethambutol' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '53' , 'RHZ-60/30/150' , 'Rifampicin/Isoniazid/Pyrazinamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '54' , 'RHZ-75/50/150' , 'Rifampicin/Isoniazid/Pyrazinamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '55' , 'RHZE-150/75/400/275' , 'Rifampicin/Isoniazid/Pyrazinamide/Ethambutol' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '56' , 'Rbt-150' , 'Rifabutin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '57' , 'Rpt-150' , 'Rifapentine' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '58' , 'S-1' , 'Streptomycin' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '59' , 'Trd- 250' , 'Terizidone' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '60' , 'Z-150' , 'Pyrazinamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '61' , 'Z-400' , 'Pyrazinamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '62' , 'Z-500' , 'Pyrazinamide' ); 
INSERT INTO  MED (ID, NAME, INN)  VALUES ( '63' , 'Z-750' , 'Pyrazinamide' ); 
