DROP TABLE IF EXIST TBTYPE;
CREATE TABLE TBTYPE (ID INTEGER PRIMARY KEY, TBTYPE VARCHAR(8), NAME VARCHAR(32));
INSERT INTO TBTYPE VALUES ('1', 'DSTB', 'Drug-Susceptible TB'); 
INSERT INTO TBTYPE VALUES ('2', 'DRTB', 'Drug-Resistant TB'); 
INSERT INTO TBTYPE VALUES ('3', 'LTBI', 'Latent TB Infection'); 

DROP TABLE IF EXISTS GUIDE;
CREATE TABLE GUIDE (ID INTEGER PRIMARY KEY, TBTYPE_ID INTEGER REFERENCES TBTYPE(ID), NAME VARCHAR(128), YEAR INTEGER);
INSERT INTO GUIDE VALUES ('1', '1', 'WHO Guideline for Drug-Susceptible TB 2010', 2010 );
INSERT INTO GUIDE VALUES ('2', '1', 'WHO Guideline for Drug-Susceptible TB 2017', 2017 );
INSERT INTO GUIDE VALUES ('3', '2', 'WHO Guideline for Drug-Resistant TB 2014', 2014 );
INSERT INTO GUIDE VALUES ('4', '2', 'WHO Guideline for Drug-Resistant TB 2016', 2016 );
INSERT INTO GUIDE VALUES ('5', '2', 'WHO Rapid Communication on Drug-Resistant TB 2018', 2018 );
INSERT INTO GUIDE VALUES ('6', '3', 'WHO Guidelines Latent TB Infection 2018', 2018 );
INSERT INTO GUIDE VALUES ('7', '2', 'WHO Rapid Communication on Drug-Resistant TB 2018 and Expert Opinion', 2018 );
INSERT INTO GUIDE VALUES ('8', '2', 'WHO consolidated guidelines on Drug-Resistant TB treatment', 2019 );


DROP TABLE IF EXISTS GUIDEDOSE;
CREATE TABLE GUIDEDOSE (ID SERIAL PRIMARY KEY, GUIDE_ID INTEGER REFERENCES GUIDE(ID), MED_ID INTEGER REFERENCES MED(ID), WEIGHTBAND VARCHAR(16), TYPE VARCHAR(32), DAILYDOSE FLOAT, DURATION FLOAT);
-- Adult DSTB
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '55', '25-39', '',  '2', '2');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '55', '40-54', '',  '3', '2');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '55', '55-70', '',  '4', '2');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '55', '71-', '',  '5', '2');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '47', '25-39', '',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '47', '40-54', '',  '3', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '47', '55-70', '',  '4', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '47', '71-', '',  '5', '4');
-- Paediatric DSTB 
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '54', '4-7', '',  '1', '2');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '54', '8-11', '',  '3', '2');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '54', '12-15', '',  '4', '2');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '54', '16-24', '',  '4', '2');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '51', '4-7', '',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '51', '8-11', '',  '3', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '51', '12-15', '',  '4', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '51', '16-24', '',  '4', '4');

-- DRTB 2019
-- Lfx-250 29
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '29', '30-35', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '29', '36-45', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '29', '46-55', '',  '4', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '29', '56-70', '',  '4', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '29', '70-', '',  '4', '20');

-- Lfx-500 30
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '30', '30-35', '',  '1.5', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '30', '36-45', '',  '1.5', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '30', '46-55', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '30', '56-70', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '30', '70-', '',  '2', '20');

-- Lfx-750 31
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '31', '30-35', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '31', '36-45', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '31', '46-55', '',  '1.5', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '31', '56-70', '',  '1.5', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '31', '70-', '',  '1.5', '20');

-- Mfx-400 34
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '34', '30-35', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '34', '36-45', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '34', '46-55', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('2', '34', '56-70', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '70-', '',  '1', '20');
-- Mfx-400 34 High
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '30-35', 'High',  '1.5', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '36-45', 'High',  '1.5', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '46-55', 'High',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '56-70', 'High',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '70-', 'High',  '2', '20');
-- Mfx-400 34 High STR
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '30-35', 'High, STR',  '1.5', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '36-45', 'High, STR',  '1.5', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '46-55', 'High, STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '56-70', 'High, STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '34', '70-', 'High, STR',  '2', '9');

-- Bdq-100 5
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '30-35', '',  '4', '0.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '36-45', '',  '4', '0.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '46-55', '',  '4', '0.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '56-70', '',  '4', '0.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '70-', '',  '4', '0.5');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '30-35', '',  '0.87', '5.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '36-45', '',  '0.87', '5.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '46-55', '',  '0.87', '5.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '56-70', '',  '0.87', '5.5');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '70-', '',  '0.87', '5.5');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '30-35', '',  '1.04', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '36-45', '',  '1.04', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '46-55', '',  '1.04', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '56-70', '',  '1.04', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '70-', '',  '1.04', '6');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '30-35', 'STR',  '1.57', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '36-45', 'STR',  '1.57', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '46-55', 'STR',  '1.57', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '56-70', 'STR',  '1.57', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '5', '70-', 'STR',  '1.57', '4');

-- Lnz-100 32
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '30-35', '',  '1', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '36-45', '',  '1', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '46-55', '',  '1', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '56-70', '',  '1', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '70-', '',  '1', '6');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '30-35', '',  '1', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '36-45', '',  '1', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '46-55', '',  '1', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '56-70', '',  '1', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '70-', '',  '1', '12');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '30-35', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '36-45', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '46-55', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '56-70', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '32', '70-', 'STR',  '1', '4');

-- Cfz-50 7
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '30-35', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '36-45', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '46-55', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '56-70', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '70-', '',  '2', '20');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '30-35', 'STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '36-45', 'STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '46-55', 'STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '56-70', 'STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '70-', 'STR',  '2', '9');

-- Cfz-100 6
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '30-35', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '36-45', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '46-55', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '56-70', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '70-', '',  '1', '20');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '30-35', 'STR',  '1', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '36-45', 'STR',  '1', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '46-55', 'STR',  '1', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '56-70', 'STR',  '1', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '7', '70-', 'STR',  '1', '9');

-- Cs-125 13
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '13', '30-35', '',  '4', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '13', '36-45', '',  '5', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '13', '46-55', '',  '6', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '13', '56-70', '',  '6', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '13', '70-', '',  '6', '20');

-- Cs-250 14
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '14', '30-35', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '14', '36-45', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '14', '46-55', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '14', '56-70', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '14', '70-', '',  '3', '20');

-- Trd-250 59
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '59', '30-35', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '59', '36-45', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '59', '46-55', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '59', '56-70', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '59', '70-', '',  '3', '20');

-- E-100 16
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '30-35', '',  '8', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '36-45', '',  '8', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '46-55', '',  '12', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '56-70', '',  '12', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '70-', '',  '12', '20');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '30-35', 'STR',  '8', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '36-45', 'STR',  '8', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '46-55', 'STR',  '12', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '56-70', 'STR',  '12', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '16', '70-', 'STR',  '12', '9');

-- E-400 17
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '30-35', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '36-45', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '46-55', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '56-70', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '70-', '',  '3', '20');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '30-35', 'STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '36-45', 'STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '46-55', 'STR',  '3', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '56-70', 'STR',  '3', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '17', '70-', 'STR',  '3', '9');

-- Dlm-50 15
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '15', '30-35', '',  '4', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '15', '36-45', '',  '4', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '15', '46-55', '',  '4', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '15', '56-70', '',  '4', '6');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '15', '70-', '',  '4', '6');

-- Z-400 61
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '61', '30-35', 'STR',  '3', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '61', '36-45', 'STR',  '4', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '61', '46-55', 'STR',  '4', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '61', '56-70', 'STR',  '4', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '61', '70-', 'STR',  '5', '9');

-- Z-500 62
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '62', '30-35', 'STR',  '2', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '62', '36-45', 'STR',  '3', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '62', '46-55', 'STR',  '3', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '62', '56-70', 'STR',  '3', '9');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '62', '70-', 'STR',  '4', '9');

-- Imp/Cls-500/500 25
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '25', '30-35', '',  '4', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '25', '36-45', '',  '4', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '25', '46-55', '',  '4', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '25', '56-70', '',  '4', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '25', '70-', '',  '4', '20');

-- Mrp-1 35
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '35', '30-35', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '35', '36-45', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '35', '46-55', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '35', '56-70', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '35', '70-', '',  '3', '20');

-- Am-500 1
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '1', '30-35', 'STR',  '1.25', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '1', '36-45', 'STR',  '1.5', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '1', '46-55', 'STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '1', '56-70', 'STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '1', '70-', 'STR',  '2', '4');

-- S-1 58
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '58', '30-35', '',  '0.6', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '58', '36-45', '',  '0.8', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '58', '46-55', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '58', '56-70', '',  '1', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '58', '70-', '',  '1', '20');

-- Eto-125 20
-- Eto-250 21
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '21', '30-35', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '21', '36-45', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '21', '46-55', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '21', '56-70', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '21', '70-', '',  '4', '20');

-- Pto-250 41
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '30-35', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '36-45', '',  '2', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '46-55', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '56-70', '',  '3', '20');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '70-', '',  '4', '20');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '30-35', 'STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '36-45', 'STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '46-55', 'STR',  '3', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '56-70', 'STR',  '3', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '41', '70-', 'STR',  '4', '4');

-- PAS-(NA)-4 38
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '38', '30-35', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '38', '36-45', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '38', '46-55', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '38', '56-70', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '38', '70-', '',  '3', '12');

-- PAS-(H)-4 39
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '39', '30-35', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '39', '36-45', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '39', '46-55', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '39', '56-70', '',  '2', '12');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '39', '70-', '',  '3', '12');

-- H-300 23
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '30-35', 'STR',  '0.7', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '36-45', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '46-55', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '56-70', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '70-', 'STR',  '1', '4');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '30-35', 'High, STR',  '1.5', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '36-45', 'High, STR',  '1.5', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '46-55', 'High, STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '56-70', 'High, STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('8', '23', '70-', 'High, STR',  '2', '4');

-- Km-0.5 26
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '30-35', '',  '1', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '36-45', '',  '1.5', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '46-55', '',  '2', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '56-70', '',  '2', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '70-', '',  '3', '8');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '30-35', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '36-45', 'STR',  '1.5', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '46-55', 'STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '56-70', 'STR',  '2', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '26', '70-', 'STR',  '3', '4');

-- Km-1 27
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '30-35', '',  '0.63', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '36-45', '',  '0.75', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '46-55', '',  '1', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '56-70', '',  '1', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '70-', '',  '1', '8');

INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '30-35', 'STR',  '0.63', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '36-45', 'STR',  '0.75', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '46-55', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '56-70', 'STR',  '1', '4');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '27', '70-', 'STR',  '1', '4');

-- Cm-0.5 10
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '10', '30-35', '',  '1.25', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '10', '36-45', '',  '1.5', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '10', '46-55', '',  '2', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '10', '56-70', '',  '2', '8');
INSERT INTO GUIDEDOSE (GUIDE_ID, MED_ID, WEIGHTBAND, TYPE, DAILYDOSE, DURATION) VALUES ('3', '10', '70-', '',  '2', '8');
-- Cm-0.75 11
-- Cm-1 12

